Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<MachineEngineer>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Status { get; set; }
    public string[] StatusOptions = new[] { "Operational", "Malfunctioning", "Being repaired" };
    public virtual ICollection<MachineEngineer> JoinEntities { get; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }
    
    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit (Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "FullName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.MachineEngineers.Add(new MachineEngineer() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId, int machineId)
    {
      var joinEntry = _db.MachineEngineers.FirstOrDefault(joinEntry => joinEntry.MachineEngineerId == joinId);
      _db.MachineEngineers.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machineId });
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Add Engineer</h2>
<h3>Assign a licensed engineer to this machine</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @Html.Label("Select an engineer")
  @Html.DropDownList("EngineerId")
  <button type="submit" value="Add Engineer" class="btn btn-primary">Add</button>
}

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1>Dr. Sillystringz's Factory</h1>
<hr/>
<h3>Add a new machine</h3>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  <br>
  <button type="submit" value="Create" class="btn btn-primary">Create</button>
}

<p>@Html.ActionLink("Back to all machines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Delete</h2>
<h3>Are you sure you want to delete this machine?</h3>

<h4>Machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <button type="submit" value="Yes" class="btn btn-success">Yes</button>
}
<button class="btn btn-danger">@Html.ActionLink("No", "Details", new { id = Model.MachineId })</button>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Machine Details</h2>

<h4>Name: @Html.DisplayFor(model => model.Name)</h4>
<h4>Description: @Html.DisplayFor(model => model.Description)</h4>
<h4>Status: @Html.DisplayFor(model => model.Status)</h4>

@if (@Model.JoinEntities.Count == 0)
{
  <p>No engineers have been licensed to work on this machine.</p>
}
else
{
  <h4>Licensed engineers:</h4>
  <ul>
    @foreach(var join in @Model.JoinEntities)
    {
      <li>@join.Engineer.FullName</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("machineId", @Model.MachineId)
        @Html.Hidden("joinId", @join.MachineEngineerId)
        <button type="submit" value="Delete" class="btn btn-danger">Delete</button>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to all machines", "Index")</p>
<p>@Html.ActionLink("Edit machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Add engineer", "AddEngineer", new { id = Model.MachineId})</p>
<p>@Html.ActionLink("Delete machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h1>Dr. Sillystringz's Factory</h1>
<hr/>
<h3>Edit Machine</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)
  <br>
  @Html.LabelFor(model => model.Status, "Status:")
  <br>
  @foreach (var status in Model.StatusOptions)
  {
    @Html.RadioButtonFor(model => model.Status, status) @status<br>
  }
  <button type="submit" value="Create" class="btn btn-primary">Save</button>
}

<p>@Html.ActionLink("Back to details", "Details", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Back to all machines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Machines</h2>

@if (@Model.Count == 0)
{
  <h3>Dr. Sillystringz hasn't installed any machines yet!</h3>
}

@foreach (Machine machine in @Model)
{
  <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</li>
}

<p>@Html.ActionLink("Add new machine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>