Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<MachineEngineer>();
    }

    public int EngineerId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string FullName
    {
      get { return FirstName + " " + LastName; }
    }
    public string Title { get; set; }

    public string Status { get; set; }
    public string[] StatusOptions = new[] { "Idle", "Active" };
    public virtual ICollection<MachineEngineer> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Description");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MachineEngineers.Add(new MachineEngineer() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MachineEngineers.Add(new MachineEngineer() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId, int engineerId)
    {
      var joinEntry = _db.MachineEngineers.FirstOrDefault(joinEntry => joinEntry.MachineEngineerId == joinId);
      _db.MachineEngineers.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineerId });
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Add Machine</h2>
<h3>Add a machine to this engineer</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  @Html.Label("Select a machine")
  @Html.DropDownList("MachineId")
  <button type="submit" value="Add Machine" class="btn btn-primary">Add</button>
}

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1>Dr. Sillystringz's Factory</h1>
<hr/>
<h3>Add a new engineer</h3>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.FirstName, "First Name")
  @Html.TextBoxFor(model => model.FirstName)
  <br>
  @Html.LabelFor(model => model.LastName, "Last Name")
  @Html.TextBoxFor(model => model.LastName)
  <br>
  @Html.LabelFor(model => model.Title)
  @Html.TextBoxFor(model => model.Title)
  <br>
  <button type="submit" value="Create" class="btn btn-primary">Create</button>
}

<p>@Html.ActionLink("Back to all engineers", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Delete</h2>
<h3>Are you sure you want to delete this engineer?</h3>

<h4>Engineer: @Html.DisplayFor(model => model.FullName)</h4>

@using (Html.BeginForm())
{
  <button type="submit" value="Yes" class="btn btn-success"> Yes</button>
}
<button class="btn btn-danger">@Html.ActionLink("No", "Details", new { id = Model.EngineerId })</button>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h2>Engineer Details</h2>

<h4>First Name: @Html.DisplayFor(model => model.FirstName)</h4>
<h4>Last Name: @Html.DisplayFor(model => model.LastName)</h4>
<h4>Title: @Html.DisplayFor(model => model.Title)</h4>
<h4>Status: @Html.DisplayFor(model => model.Status)</h4>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer hasn't been licensed to repair any machines.</p>
}
else
{
  <h4>Licensed to repair:</h4>
  <ul>
    @foreach(var join in @Model.JoinEntities)
    {
      <li>@join.Machine.Name</li>
      @using (Html.BeginForm("DeleteMachine", "Engineers"))
      {
        @Html.Hidden("engineerId", @Model.EngineerId)
        @Html.Hidden("joinId", @join.MachineEngineerId)
        <button type="submit" value="Delete" class="btn btn-danger">Delete</button>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to all engineers", "Index")</p>
<p>@Html.ActionLink("Edit engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Add machine", "AddMachine", new { id = Model.EngineerId})</p>
<p>@Html.ActionLink("Delete engineer", "Delete", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h1>Dr. Sillystringz's Factory</h1>
<hr />
<h3>Edit Engineer</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.FirstName, "First Name")
  @Html.EditorFor(model => model.FirstName)
  <br>
  @Html.LabelFor(model => model.LastName, "Last Name")
  @Html.EditorFor(model => model.LastName)
  <br>
  @Html.LabelFor(model => model.Title)
  @Html.EditorFor(model => model.Title)
  <br>
  @Html.LabelFor(model => model.Status, "Status:")
  <br>
  @foreach (var status in Model.StatusOptions)
  {
    @Html.RadioButtonFor(model => model.Status, status) @status<br>
  }
  <button type="submit" value="Save" class="btn btn-primary">Save</button>
}

<p>@Html.ActionLink("Back to details", "Details", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Back to all engineers", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Dr. Sillystringz's Factory</h1>
<h2>Engineers</h2>

@if (@Model.Count == 0)
{
  <h3>Dr. Sillystringz hasn't hired any engineers yet!</h3>
}

@foreach (Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.FullName}", "Details", new { id = engineer.EngineerId })</li>
}

<p>@Html.ActionLink("Add new engineer", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>